server:
  context-path: /otc
  port: 6006

spring:
  application:
    name: otc
  session:
    timeout: 60
    store-type: redis

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    password: 65Yxd4PMYbTNAYHT
    url: jdbc:p6spy:mysql://194.41.36.123:3306/zhengtuo?characterEncoding=utf-8&useSSL=false
    username: zhengtuo

  jpa:
    generate-ddl: false
    show-sql: true

  data:
    mongodb:
      uri: mongodb://194.41.36.123:27017/bitrade

  ## redis\u670D\u52A1\u5668\u914D\u7F6E
  redis:
    database: 0
    host: 194.41.36.123
    password: Wrhwiydk6Z2
    port: 6379
    timeout: 30000


decorator:
  datasource:
    p6spy:
      log-file: spy.log
      log-format: executionTime:%(executionTime) | sql:%(sqlSingleLine)
      logging: file
